image: docker:19-dind

variables:
  REPOSITORY_URL: sua repository url
  REGION: us-east-1

services:
- name: docker:19-dind
  alias: docker
  command: ["--tls=false"]
variables:
        DOCKER_DRIVER: overlay2
        DOCKER_TLS_CERTDIR: ""
        GIT_SSL_NO_VERIFY: "1"

before_script:
  - apk add --no-cache py-pip tzdata jq
  - pip install awscli

stages:
  - build

build:
  stage: build
  script:
    - $(aws ecr get-login --no-include-email --region us-east-1)
    - echo "Building image..."
    - docker build -t api-powerbi .
    - echo "Tagging image..."
    - docker tag imagem
    - echo "Pushing image..."
    - docker push imagem
    - docker rmi -f imagem
  only:
    - main
  tags:
    - docker


